---
apiVersion: v1
kind: Namespace
metadata:
  name: eviction-webhook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eviction-webhook
  namespace: eviction-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eviction-webhook
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eviction-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eviction-webhook
subjects:
  - kind: ServiceAccount
    name: eviction-webhook
    namespace: eviction-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: eviction-webhook
  namespace: eviction-webhook
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: eviction-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eviction-webhook
  namespace: eviction-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eviction-webhook
  template:
    metadata:
      labels:
        app: eviction-webhook
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8443"
        prometheus.io/scheme: "https"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: eviction-webhook
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      containers:
        - name: server
          image: quay.io/mrincompetent/eviction-webhook:v0.0.3
          command: [ "/eviction-webhook" ]
          args: [
            "-listen-address", "0.0.0.0:8443",
            "-tls.cert-path", "/etc/webhook/certs/tls.crt",
            "-tls.key-path", "/etc/webhook/certs/tls.key",
          ]
          ports:
            - containerPort: 8443
              name: webhook
          readinessProbe:
            httpGet:
              path: /ready
              port: webhook
              scheme: HTTPS
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sleep", "10" ]
          volumeMounts:
            - name: certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: eviction-webhook-certs
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: eviction-webhook-self-signed-issuer
  namespace: eviction-webhook
spec:
  selfSigned: { }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eviction-webhook-root-cert
  namespace: eviction-webhook
spec:
  secretName: eviction-webhook-root-cert
  issuerRef:
    name: eviction-webhook-self-signed-issuer
  commonName: "ca.webhook.eviction-webhook"
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: eviction-webhook-root-issuer
  namespace: eviction-webhook
spec:
  ca:
    secretName: eviction-webhook-root-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eviction-webhook-cert
  namespace: eviction-webhook
spec:
  secretName: eviction-webhook-certs
  duration: 1h0m0s
  renewBefore: 55m
  issuerRef:
    name: eviction-webhook-root-issuer
  dnsNames:
    - eviction-webhook
    - eviction-webhook.eviction-webhook
    - eviction-webhook.eviction-webhook.svc
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "eviction-webhook.mrincompetent.io"
  annotations:
    cert-manager.io/inject-ca-from: eviction-webhook/eviction-webhook-cert
webhooks:
  - name: "eviction-webhook.mrincompetent.io"
    rules:
      - apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "pods/eviction" ]
        scope: "Namespaced"
    clientConfig:
      service:
        name: eviction-webhook
        namespace: eviction-webhook
        path: "/validate-eviction"
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    timeoutSeconds: 30
