name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo
      - name: Log in to Image registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: quay.io/mrincompetent/eviction-webhook
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
